#!/usr/bin/env python3
"""Generate firmware/partitions.csv from ONE number: the flash size.

    python3 tools/fw/gen_partitions.py --flash 4MB            # writes firmware/partitions.csv
    python3 tools/fw/gen_partitions.py --flash 16MB --check   # compares, exit 1 on drift

The flash size of the Panda Status P2 is UNKNOWN until Phase 0 reads it off the device
(docs/PLAN.md, Phase 0). No number in this repository establishes it: the 0x480000,
0x6E0000 and 0x180000 upload caps in the factory page are shared framework constants
(docs/protocol-websocket.md, "The 0x480000 question"). The committed CSV is PROVISIONAL and
says so in its header; regenerating for the real size is this one command.

Layout, in flash order:
    nvs        0x9000   0x6000     settings blob and Wi-Fi credentials
    otadata    0xF000   0x2000     which app slot boots
    phy_init   0x11000  0x1000     RF calibration
    ota_0      0x20000  OTA        app slot A
    ota_1      ...      OTA        app slot B, same size, 0x10000 aligned
    images     ...      the rest   image pack and the fifteen stage animations, raw
    coredump   end-4K   0x1000     last 4 KiB
"""
import argparse, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "firmware", "partitions.csv")
SIZES = {"2MB": 0x200000, "4MB": 0x400000, "8MB": 0x800000, "16MB": 0x1000000}

def build(flash, ota):
    if flash not in SIZES: sys.exit(f"flash must be one of {', '.join(SIZES)}")
    total = SIZES[flash]
    rows = [("nvs", "data", "nvs", 0x9000, 0x6000), ("otadata", "data", "ota", 0xF000, 0x2000), ("phy_init", "data", "phy", 0x11000, 0x1000)]
    ota0 = 0x20000; ota1 = ota0 + ota
    if ota1 % 0x10000: sys.exit("OTA slot size must keep ota_1 0x10000 aligned")
    images = ota1 + ota
    core = total - 0x1000
    if images + 0x10000 > core: sys.exit(f"{flash} cannot hold two {ota:#x} slots and an images partition")
    rows += [("ota_0", "app", "ota_0", ota0, ota), ("ota_1", "app", "ota_1", ota1, ota),
             ("images", "0x40", "0x00", images, core - images), ("coredump", "data", "coredump", core, 0x1000)]
    head = [f"# PROVISIONAL. Generated by tools/fw/gen_partitions.py --flash {flash} --ota {ota:#x}.",
            "# The P2's flash size is unknown until Phase 0 reads it off the device; nothing in this",
            "# repository establishes it. Regenerate with the real size, then delete this word.",
            "# Two app slots so OTA is a plain upload in both directions; images holds the stage",
            "# animations raw (custom type 0x40); coredump is the last 4 KiB.",
            "# Name,     Type, SubType,  Offset,   Size"]
    body = [f"{n+',':<11}{t+',':<6}{s+',':<9}{o:#x},{z:#x}".replace(",0x", ", 0x") for n, t, s, o, z in rows]
    return "\n".join(head + body) + "\n"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--flash", default="4MB", choices=list(SIZES))
    ap.add_argument("--ota", type=lambda s: int(s, 0), default=0x180000, help="bytes per app slot, default 0x180000")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = build(a.flash, a.ota)
    if a.check:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text: print("DRIFT: firmware/partitions.csv is not what the generator produces"); return 1
        print("firmware/partitions.csv matches the generator"); return 0
    open(OUT, "w").write(text); print(text, end=""); return 0

if __name__ == "__main__":
    sys.exit(main())
