#!/usr/bin/env bash
#
# test-flash-tools.sh: prove tools/fw/ without a device.
#
# A synthetic 4 MB flash image is built from the committed partition table, the built app
# image in both slots, fifteen small animations and random NVS. The mock device serves it
# at GET /backup and can let an ota_fw upload land or not. Against that: the image library,
# the golden capture (whole, short, absent), the off-machine copy, the preflight gate on its
# positive path and on every single refusal, the install script's three verdicts, and the
# partition table read out of a dump. Nothing here touches hardware; the USB paths are
# covered only up to the point where esptool would be called.
#
#   make test-flash-tools        or        bash tools/fw/test-flash-tools.sh
#
# Needs: firmware/build/pandastatusos.bin (idf.py build), node with private/uiwork/node_modules.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"; ROOT="$(cd "$HERE/../.." && pwd)"
FI="python3 $HERE/flashimage.py"
BIN="$ROOT/firmware/build/pandastatusos.bin"
[ -f "$BIN" ] || { echo "no $BIN: build the firmware first (docs/BUILDING.md)"; exit 2; }
DEPS="$ROOT/private/uiwork/node_modules"; [ -d "$DEPS" ] || { echo "no $DEPS (see CONTRIBUTING.md)"; exit 2; }
T="$(mktemp -d)"; trap 'stop_mock; if [ "${fail:-0}" -eq 0 ]; then rm -rf "$T"; else echo "kept for inspection: $T"; fi' EXIT
PORT=8198; MOCK_PID=""
pass=0; fail=0
ok()   { pass=$((pass+1)); printf '  ok    %s\n' "$1"; }
bad()  { fail=$((fail+1)); printf '  FAIL  %s\n        %s\n' "$1" "${2:-}"; }
t()    { if [ "$2" -eq 0 ]; then ok "$1"; else bad "$1" "${3:-}"; fi; }

start_mock() {   # KEY=VALUE ...
    stop_mock || return 1
    if curl -s -m 1 -o /dev/null "http://127.0.0.1:$PORT/__state"; then echo "something already answers on port $PORT; not starting a mock on top of it" >&2; return 1; fi
    # no subshell: $! must be node's own PID, or the kill below leaves node running on the port
    env NODE_PATH="$DEPS" PS_PORT=$PORT PS_STATE=p2-idle.json PS_QUIET=1 "$@" node "$ROOT/tools/ui/mock/mockdev.js" > "$T/mock.log" 2>&1 &
    MOCK_PID=$!
    for _ in $(seq 1 40); do curl -s -m 1 -o /dev/null "http://127.0.0.1:$PORT/__state" && return 0; sleep 0.15; done
    echo "mock did not start:"; cat "$T/mock.log"; return 1
}
stop_mock() {
    if [ -n "$MOCK_PID" ]; then kill "$MOCK_PID" 2>/dev/null; wait "$MOCK_PID" 2>/dev/null; MOCK_PID=""; fi
    for _ in $(seq 1 20); do curl -s -m 1 -o /dev/null "http://127.0.0.1:$PORT/__state" || return 0; sleep 0.1; done
    echo "something still answers on port $PORT after the mock was stopped" >&2; return 1
}

# The synthetic device this suite tests the tools against. It is a FIXTURE, deliberately not
# the product's own firmware/partitions.csv: a test of the flash tools must not change
# meaning when the product's layout changes, and it did. When the real table was read off a
# unit it turned out to have five partitions and no images partition, and three cases here
# started failing although nothing about the tools had changed. The fixture also keeps the
# tools covered against a layout WITH an images partition and fifteen animations, which is
# a shape they must still parse. It says PROVISIONAL because one check needs a table that
# does.
#
# The app slots are 0x1d0000 and not the 0x180000 they were, because the app outgrew them.
# A slot too small to hold the built image makes `extract` refuse, and the byte-for-byte
# case fails for a reason that has nothing to do with the tools under test. They are sized
# like the real table's slots, about 16% clear of today's image, and the images partition
# gives up the room: the fifteen animations written here are a few bytes each.
cat > "$T/fixture-partitions.csv" <<'CSV'
# PROVISIONAL. Generated by tools/fw/gen_partitions.py --flash 4MB --ota 0x180000.
# The P2's flash size is unknown until Phase 0 reads it off the device; nothing in this
# repository establishes it. Regenerate with the real size, then delete this word.
# Two app slots so OTA is a plain upload in both directions; images holds the stage
# animations raw (custom type 0x40); coredump is the last 4 KiB.
# Name,     Type, SubType,  Offset,   Size
nvs,       data, nvs,     0x9000, 0x6000
otadata,   data, ota,     0xf000, 0x2000
phy_init,  data, phy,     0x11000, 0x1000
ota_0,     app,  ota_0,   0x20000, 0x1d0000
ota_1,     app,  ota_1,   0x1f0000, 0x1d0000
images,    0x40, 0x00,    0x3c0000, 0x3f000
coredump,  data, coredump, 0x3ff000, 0x1000
CSV
# The two numbers in that table the rest of this file has to agree with. They were typed out
# by hand in four places, and three of them went stale the moment the app slots changed.
FIX_OTA1=0x1f0000        # where the second app slot starts
FIX_SLOT=0x1d0000        # how big each app slot is

echo "== the synthetic image"
python3 - "$ROOT" "$BIN" "$T/flash.bin" "$T/fixture-partitions.csv" <<'PY'
import sys, os, struct, random
sys.path.insert(0, os.path.join(sys.argv[1], 'tools', 'fw')); import flashimage as fi
root, app, out, fixture = sys.argv[1:5]
table = fi.parse_csv(open(fixture).read())
img = bytearray(b'\xff' * 0x400000)
img[0] = 0xE9; img[1:0x1000] = bytes(0xFFF)                      # a bootloader-shaped region
img[0x8000:0x8000 + 0xC00] = fi.encode_table(table)
by = {e['name']: e for e in table}
random.seed(7); img[by['nvs']['offset']:by['nvs']['offset'] + 0x1000] = bytes(random.getrandbits(8) for _ in range(0x1000))
seq = struct.pack('<I', 1); crc = struct.pack('<I', __import__('zlib').crc32(seq, 0xFFFFFFFF) & 0xFFFFFFFF)
img[by['otadata']['offset']:by['otadata']['offset'] + 32] = seq + b'\xff' * 20 + b'\xff\xff\xff\xff' + crc   # seq 1: ota_0 boots
a = open(app, 'rb').read()
for s in ('ota_0', 'ota_1'): img[by[s]['offset']:by[s]['offset'] + len(a)] = a
def gif(w):  # a whole, minimal GIF, w x 1, no colour table
    return b'GIF89a' + struct.pack('<HHBBB', w, 1, 0, 0, 0) + b'\x2c' + struct.pack('<HHHHB', 0, 0, w, 1, 0) + b'\x02\x02\x44\x01\x00' + b'\x3b'
off = by['images']['offset']
for i in range(15):
    g = gif(i + 1); img[off:off + len(g)] = g; off += 0x1000
open(out, 'wb').write(img)
print(f"  {len(img)} bytes, app {len(a)} bytes in both slots, 15 animations")
PY
IMG="$T/flash.bin"

echo "== the image library"
J="$($FI inspect --json "$IMG")"
py() { echo "$J" | python3 -c "import json,sys; r=json.load(sys.stdin); print($1)"; }
t "parses 7 partitions with a good md5" "$([ "$(py 'len(r["table"])')" = 7 ] && [ "$(py 'r["md5_ok"]')" = True ]; echo $?)"
t "both app slots carry pandastatusos, the same build" "$([ "$(py 'r["same_build"]')" = True ] && [ "$(py 'r["apps"][1]["desc"]["project"]')" = pandastatusos ]; echo $?)"
t "finds the fifteen animations" "$([ "$(py 'len(r["gifs"])')" = 15 ]; echo $?)" "$(py 'len(r["gifs"])')"
t "the fifteen hashes are distinct" "$([ "$(py 'len({g["sha256"] for g in r["gifs"]})')" = 15 ]; echo $?)"
t "bootloader magic seen at 0x0" "$([ "$(py 'r["bootloader_magic"]')" = True ]; echo $?)"
NAMES_C="$(sed -n '/ps_gif_slot_names\[PS_GIF_SLOTS\] = {/,/};/p' "$ROOT/firmware/main/ps_cfg.c" | command grep -o '"[a-z_]*"' | tr -d '"' | tr '\n' ' ')"
NAMES_PY="$(python3 -c "import sys; sys.path.insert(0,'$HERE'); import flashimage as f; print(' '.join(f.SLOTS)+' ')")"
t "slot names agree with firmware/main/ps_cfg.c" "$([ "$NAMES_C" = "$NAMES_PY" ]; echo $?)" "C: $NAMES_C / py: $NAMES_PY"
( . ~/esp/esp-idf/export.sh >/dev/null 2>&1; python3 ~/esp/esp-idf/components/partition_table/gen_esp32part.py -q "$ROOT/firmware/partitions.csv" "$T/idf.bin" ) 2>/dev/null
$FI encode "$ROOT/firmware/partitions.csv" "$T/ours.bin"
t "encode matches ESP-IDF's gen_esp32part.py byte for byte" "$(cmp -s "$T/idf.bin" "$T/ours.bin"; echo $?)"
dd if="$IMG" bs=1 skip=$((0xF000)) count=8192 of="$T/otadata.bin" 2>/dev/null
t "otadata: seq 1 boots ota_0" "$([ "$($FI otadata "$T/otadata.bin" 2 | awk -F= '/ACTIVE/{print $2}')" = 0 ]; echo $?)"
python3 -c "import struct,zlib,sys; s=struct.pack('<I',2); open(sys.argv[1],'wb').write(b'\xff'*0x1000+s+b'\xff'*20+b'\xff'*4+struct.pack('<I',zlib.crc32(s,0xFFFFFFFF)&0xFFFFFFFF))" "$T/ota2.bin"
t "otadata: seq 2 in the second entry boots ota_1" "$([ "$($FI otadata "$T/ota2.bin" 2 | awk -F= '/ACTIVE/{print $2}')" = 1 ]; echo $?)"
printf '\xff%.0s' $(seq 1 8192) > "$T/otaff.bin"
t "otadata: erased means no valid entry" "$([ "$($FI otadata "$T/otaff.bin" 2 | awk -F= '/ACTIVE/{print $2}')" = none ]; echo $?)"
eval "$($FI appdesc "$BIN" | sed 's/^/A_/')"
t "appdesc reads the built image's identity and page" "$([ "$A_PROJECT" = pandastatusos ] && [ ${#A_BUILD} -eq 16 ] && [ "$A_PAGE_SHA256" != none ]; echo $?)"
t "appdesc page equals firmware/main/ui.html" "$([ "$A_PAGE_SHA256" = "$(shasum -a 256 "$ROOT/firmware/main/ui.html" | awk '{print $1}')" ]; echo $?)"
head -c 4096 /dev/urandom > "$T/noise.bin"
$FI csv "$IMG" > "$T/from-image.csv"
t "csv: the table written from an image parses back to the same table" "$(python3 -c "import sys; sys.path.insert(0,'$HERE'); import flashimage as f; img=open('$IMG','rb').read(); e,_=f.parse_table(img); sys.exit(0 if f.same_table(f.parse_csv(open('$T/from-image.csv').read()), e) else 1)"; echo $?)"
$FI extract "$IMG" ota_1 "$T/ota1.bin" >/dev/null
t "extract: an app slot comes out cut exactly at the app image's end" "$(cmp -s "$T/ota1.bin" "$BIN"; echo $?)" "$(wc -c < "$T/ota1.bin" | tr -d ' ') vs $(wc -c < "$BIN" | tr -d ' ')"
t "appdesc refuses a file that is not an app image" "$($FI appdesc "$T/noise.bin" >/dev/null 2>&1; [ $? -ne 0 ]; echo $?)"

echo "== golden capture over the network, against the mock"
export PS_BACKUPS_DIR="$T/backups"
start_mock PS_BACKUP="$IMG" PS_BUILD=deadbeefdeadbeef || exit 2
bash "$HERE/golden.sh" http 127.0.0.1:$PORT --note "test one" > "$T/g1.log" 2>&1; RC=$?
G1="$(ls "$T/backups/goldens/"GOLDEN-*.bin 2>/dev/null | head -1)"
t "golden.sh http: takes the image and records it" "$RC" "$(tail -6 "$T/g1.log")"
t "golden.sh http: the file is 444 with a .sha256 beside it" "$([ -n "$G1" ] && [ "$(python3 -c 'import os,sys,stat; print(oct(stat.S_IMODE(os.stat(sys.argv[1]).st_mode)))' "$G1")" = 0o444 ] && [ -f "${G1%.bin}.sha256" ]; echo $?)"
t "golden.sh http: the sha256 record verifies" "$(cd "$T/backups/goldens" && shasum -a 256 -c "$(basename "${G1%.bin}.sha256")" >/dev/null 2>&1; echo $?)"
t "golden.sh http: manifest line written with both slots and 15 animations" "$(command grep -q 'slots_same_build=yes.*animations=15.*test one' "$T/backups/MANIFEST.tsv"; echo $?)" "$(cat "$T/backups/MANIFEST.tsv")"
sleep 1
bash "$HERE/golden.sh" http 127.0.0.1:$PORT > "$T/g2.log" 2>&1
t "golden.sh http: a second capture is a new file, never an overwrite" "$([ "$(ls "$T/backups/goldens/"GOLDEN-*.bin | wc -l | tr -d ' ')" = 2 ]; echo $?)"
t "golden.sh http: two captures of one image hash the same" "$([ "$(awk '{print $1}' "$T/backups/goldens/"*.sha256 | sort -u | wc -l | tr -d ' ')" = 1 ]; echo $?)"
curl -s -o /dev/null -X POST -H 'Content-Type: application/json' -d '{"name":"PS_BACKUP_TRUNCATE","value":"1000000"}' "http://127.0.0.1:$PORT/__knob"
bash "$HERE/golden.sh" http 127.0.0.1:$PORT > "$T/g3.log" 2>&1; RC=$?
t "golden.sh http: a short read is refused and nothing is kept" "$([ $RC -ne 0 ] && command grep -q 'SHORT READ' "$T/g3.log" && [ "$(ls "$T/backups/goldens/" | wc -l | tr -d ' ')" = 4 ]; echo $?)" "$(tail -2 "$T/g3.log")"
stop_mock
start_mock || exit 2
bash "$HERE/golden.sh" http 127.0.0.1:$PORT > "$T/g4.log" 2>&1; RC=$?
t "golden.sh http: the factory device (302, no /backup) is refused" "$([ $RC -ne 0 ]; echo $?)" "$(tail -2 "$T/g4.log")"
stop_mock
bash "$HERE/golden.sh" verify "$G1" > "$T/v1.log" 2>&1
t "golden.sh verify: a recorded image verifies and parses" "$?"
cp "$G1" "$T/corrupt.bin"; cp "${G1%.bin}.sha256" "$T/corrupt.sha256"; printf 'x' | dd of="$T/corrupt.bin" bs=1 seek=100000 conv=notrunc 2>/dev/null
bash "$HERE/golden.sh" verify "$T/corrupt.bin" > "$T/v2.log" 2>&1; RC=$?
t "golden.sh verify: one changed byte fails" "$([ $RC -ne 0 ]; echo $?)"
bash "$HERE/golden.sh" copy "$G1" "$T/offmachine" > "$T/c1.log" 2>&1
t "golden.sh copy: copies, re-hashes there, records the path" "$([ $? -eq 0 ] && command grep -q "$T/offmachine/" "$T/backups/goldens/OFFMACHINE.tsv"; echo $?)" "$(cat "$T/c1.log")"
bash "$HERE/golden.sh" copy "$G1" "$T/offmachine" > "$T/c2.log" 2>&1; RC=$?
t "golden.sh copy: refuses to overwrite an existing copy" "$([ $RC -ne 0 ]; echo $?)"

echo "== the preflight gate"
export PS_REPO_ROOT="$T/repo"
setup_positive() {
    rm -rf "$T/backups/stock" "$T/repo" "$T/off2"; mkdir -p "$T/backups/stock" "$T/repo/backups" "$T/repo/firmware" "$T/off2"
    cp "$IMG" "$T/backups/stock/GOLDEN-20260101-000001-full-4MB.bin"; cp "$IMG" "$T/backups/stock/GOLDEN-20260101-000002-full-4MB.bin"
    ( cd "$T/backups/stock" && for f in GOLDEN-*.bin; do shasum -a 256 "$f" > "${f%.bin}.sha256"; done )
    bash "$HERE/golden.sh" copy "$T/backups/stock/GOLDEN-20260101-000001-full-4MB.bin" "$T/off2" >/dev/null 2>&1
    $FI gifs "$IMG" | awk -v names="$NAMES_PY" 'BEGIN{n=split(names,a," ")} {print $1"  "a[NR]}' > "$T/backups/stock/ANIMATIONS.sha256"
    # a synthetic unit record; the address is generated so no address-shaped token sits in this file
    python3 -c "print('MAC=' + ':'.join('%02x' % (17 * i) for i in range(1, 7))); print('CHIP=ESP32-C3'); print('FLASH_SIZE=4MB')" > "$T/backups/stock/RESTORE-THIS-UNIT.txt"
    sed 's/<PENDING DUMP[^>]*>/filled/g' "$ROOT/backups/RESTORE.md" > "$T/repo/backups/RESTORE.md"
    python3 "$HERE/partitions_from_dump.py" "$IMG" >/dev/null
}
setup_positive
bash "$HERE/preflight.sh" > "$T/p0.log" 2>&1; RC=$?
t "preflight passes with a complete stock backup set" "$RC" "$(cat "$T/p0.log")"
t "preflight: all eight checks reported PASS" "$([ "$(command grep -c '^  PASS' "$T/p0.log")" = 8 ]; echo $?)"
t "partitions_from_dump.py --check agrees with the image it wrote from" "$(python3 "$HERE/partitions_from_dump.py" "$IMG" --check >/dev/null 2>&1; echo $?)"
refuse() {   # <label> <check number> <setup commands...>
    local label="$1" n="$2"; shift 2
    setup_positive; eval "$@"
    bash "$HERE/preflight.sh" > "$T/p.log" 2>&1; local rc=$?
    if [ $rc -ne 0 ] && command grep -q "^  FAIL  $n " "$T/p.log"; then ok "preflight refuses: $label (check $n)"; else bad "preflight refuses: $label (check $n)" "$(cat "$T/p.log")"; fi
}
refuse "only one read exists" 2 'rm "$T/backups/stock/GOLDEN-20260101-000002-full-4MB.bin" "$T/backups/stock/GOLDEN-20260101-000002-full-4MB.sha256"'
refuse "the two reads differ by one byte" 2 'chmod 644 "$T/backups/stock/GOLDEN-20260101-000002-full-4MB.bin"; printf "x" | dd of="$T/backups/stock/GOLDEN-20260101-000002-full-4MB.bin" bs=1 seek=500000 conv=notrunc 2>/dev/null; ( cd "$T/backups/stock" && shasum -a 256 GOLDEN-20260101-000002-full-4MB.bin > GOLDEN-20260101-000002-full-4MB.sha256 )'
refuse "a file no longer matches its own .sha256" 1 'echo "0000000000000000000000000000000000000000000000000000000000000000  x" > "$T/backups/stock/GOLDEN-20260101-000002-full-4MB.sha256"'
refuse "no .sha256 beside a file" 1 'rm "$T/backups/stock/GOLDEN-20260101-000001-full-4MB.sha256"'
# blank_slots <offset> [<offset>...]: erase those slots in both stock reads, re-hash them, and
# redo the off-machine copy, because changing the image changes the sha256 that check 4 records.
blank_slots() {
    chmod 644 "$T/backups/stock/"*.bin
    for off in "$@"; do
      python3 -c "import sys; p=sys.argv[1]; o=int(sys.argv[2],16); b=bytearray(open(p,'rb').read()); b[o:o+0x1000]=b'\xff'*0x1000; open(p,'wb').write(b)" \
        "$T/backups/stock/GOLDEN-20260101-000001-full-4MB.bin" "$off"
    done
    cp "$T/backups/stock/GOLDEN-20260101-000001-full-4MB.bin" "$T/backups/stock/GOLDEN-20260101-000002-full-4MB.bin"
    ( cd "$T/backups/stock" && for f in GOLDEN-*.bin; do shasum -a 256 "$f" > "${f%.bin}.sha256"; done )
    rm -rf "$T/off2"; mkdir -p "$T/off2"; rm -f "$T/backups/stock/OFFMACHINE.tsv"
    bash "$HERE/golden.sh" copy "$T/backups/stock/GOLDEN-20260101-000001-full-4MB.bin" "$T/off2" >/dev/null 2>&1
}
# A factory unit ships with one slot written and the other erased, which is what the first real
# dump showed. The gate has to accept that shape, and has to keep refusing a dump with no app in
# it at all. Both directions are asserted, because relaxing a safety check without pinning what
# it still refuses is how a check stops being one.
setup_positive; blank_slots "$FIX_OTA1"
bash "$HERE/preflight.sh" > "$T/p1.log" 2>&1
t "preflight accepts a factory-shaped dump: one app slot written, one erased" "$?" "$(cat "$T/p1.log")"
t "and says so rather than passing quietly" "$(command grep -q 'slot(s) empty' "$T/p1.log"; echo $?)"
refuse "no app slot holds an image at all" 3 "blank_slots 0x20000 $FIX_OTA1"
refuse "no off-machine record" 4 'rm "$T/backups/stock/OFFMACHINE.tsv"'
refuse "the off-machine copy is reachable and differs" 4 'chmod 644 "$T/off2/"*.bin; printf "x" | dd of="$T/off2/GOLDEN-20260101-000001-full-4MB.bin" bs=1 seek=700000 conv=notrunc 2>/dev/null'
refuse "fourteen animation hashes" 5 'python3 -c "import sys; p=sys.argv[1]; l=open(p).read().splitlines(True); open(p,\"w\").write(\"\".join(l[:14]))" "$T/backups/stock/ANIMATIONS.sha256"'
refuse "an animation named twice" 5 'python3 -c "import sys; p=sys.argv[1]; l=open(p).read().splitlines(True); l[14]=l[14].replace(\"printing\",\"standby\"); open(p,\"w\").write(\"\".join(l))" "$T/backups/stock/ANIMATIONS.sha256"'
refuse "RESTORE.md still carries a placeholder" 6 'echo "<PENDING DUMP>" >> "$T/repo/backups/RESTORE.md"'
refuse "partitions.csv is still the PROVISIONAL table" 7 'cp "$T/fixture-partitions.csv" "$T/repo/firmware/partitions.csv"'
refuse "partitions.csv drifted from the dump" 7 'python3 -c "import sys; p=sys.argv[1]; s=open(p).read(); open(p,\"w\").write(s.replace(\"$FIX_OTA1\",\"0x1e0000\"))" "$T/repo/firmware/partitions.csv"'
refuse "the unit is not recorded" 8 'rm "$T/backups/stock/RESTORE-THIS-UNIT.txt"'
setup_positive

echo "== the install script, against the mock"
start_mock || exit 2                                                  # the factory: 200, nothing lands
bash "$HERE/ota-install.sh" 127.0.0.1:$PORT "$BIN" > "$T/o1.log" 2>&1; RC=$?
t "ota-install: a 200 that changed nothing is NOT LANDED (exit 1)" "$([ $RC -eq 1 ] && command grep -q '^.*NOT LANDED' "$T/o1.log"; echo $?)" "$(tail -4 "$T/o1.log")"
t "ota-install: preflight ran first" "$(command grep -q 'PREFLIGHT PASSED' "$T/o1.log"; echo $?)"
stop_mock
start_mock PS_OTA_LANDS=1 PS_OTA_RESTART_MS=2500 || exit 2
bash "$HERE/ota-install.sh" 127.0.0.1:$PORT "$BIN" > "$T/o2.log" 2>&1; RC=$?
t "ota-install: an upload that lands is FLASHED (exit 0), through the restart window" "$([ $RC -eq 0 ] && command grep -q 'FLASHED' "$T/o2.log"; echo $?)" "$(tail -4 "$T/o2.log")"
t "ota-install: the verdict names the build the device now reports" "$(command grep -q "after:  build $A_BUILD" "$T/o2.log"; echo $?)"
bash "$HERE/ota-install.sh" verify 127.0.0.1:$PORT > "$T/ov.log" 2>&1; RC=$?
t "ota-install verify: re-reads the device against the recorded expectation, FLASHED" "$([ $RC -eq 0 ] && command grep -q 'FLASHED' "$T/ov.log"; echo $?)" "$(tail -3 "$T/ov.log")"
bash "$HERE/ota-install.sh" 127.0.0.1:$PORT "$BIN" > "$T/o3.log" 2>&1; RC=$?
t "ota-install: the same build again is NOT VERIFIABLE (exit 2), nothing sent" "$([ $RC -eq 2 ] && command grep -q 'NOT VERIFIABLE' "$T/o3.log" && ! command grep -q 'sending' "$T/o3.log"; echo $?)" "$(tail -3 "$T/o3.log")"
stop_mock
head -c 1000 /dev/urandom > "$T/notapp.bin"
start_mock || exit 2
bash "$HERE/ota-install.sh" 127.0.0.1:$PORT "$T/notapp.bin" > "$T/o4.log" 2>&1; RC=$?
t "ota-install: refuses a file that is not an app image, sends nothing" "$([ $RC -ne 0 ] && command grep -q 'not an app image' "$T/o4.log" && ! command grep -q 'sending' "$T/o4.log"; echo $?)" "$(tail -2 "$T/o4.log")"
python3 -c "import sys; b=open(sys.argv[1],'rb').read(); n=int(sys.argv[3],16)+1; open(sys.argv[2],'wb').write(b+b'\xff'*(n-len(b)))" "$BIN" "$T/toobig.bin" "$FIX_SLOT"
bash "$HERE/ota-install.sh" 127.0.0.1:$PORT "$T/toobig.bin" > "$T/o5.log" 2>&1; RC=$?
t "ota-install: refuses an image larger than the smallest stock app slot" "$([ $RC -ne 0 ] && command grep -q 'larger than the smallest' "$T/o5.log"; echo $?)" "$(tail -2 "$T/o5.log")"
stop_mock
bash "$HERE/ota-install.sh" 127.0.0.1:$PORT "$BIN" > "$T/o6.log" 2>&1; RC=$?
t "ota-install: a device that does not answer gets nothing sent" "$([ $RC -ne 0 ] && command grep -q 'did not answer' "$T/o6.log"; echo $?)"
rm -rf "$T/backups/stock"
bash "$HERE/ota-install.sh" 127.0.0.1:$PORT "$BIN" > "$T/o7.log" 2>&1; RC=$?
t "ota-install: a refused preflight stops it before any probe" "$([ $RC -ne 0 ] && command grep -q 'preflight refused' "$T/o7.log"; echo $?)"
bash "$HERE/usb-app-write.sh" "$BIN" > "$T/u1.log" 2>&1; RC=$?
t "usb-app-write: a refused preflight stops it before esptool" "$([ $RC -ne 0 ] && command grep -q 'preflight refused' "$T/u1.log"; echo $?)"
t "flash-log.txt records every run" "$([ "$(command grep -c 'ota-install:' "$T/backups/flash-log.txt")" -ge 6 ]; echo $?)"

echo
echo "flash tools: $pass passed, $fail failed"
[ "$fail" -eq 0 ]
