# Item 6: emit the UI string table from our own per-language files.
#   strings/en.json            the authoritative English key -> text (what the UI displays)
#   strings/<lang>.json        one file per other language, same keys, translated from English only
# Output strings/ps_strings.js: a language-major table, PS_STRINGS[lang][key], plus the language
# list PS_STRING_LANGS. Validates that every language carries every key and every placeholder.
import io, json, os, re, sys
D = sys.argv[1] if len(sys.argv) > 1 else '/Users/jeremykenedy/sites/PandaVent/private/uiwork/beer/strings'
LANGS = ['en', 'zh', 'es', 'fr', 'de', 'it', 'pt', 'nl', 'pl', 'id', 'fil', 'vi',
         'ja', 'ko', 'yue', 'ru', 'uk', 'sr', 'el', 'ar', 'th', 'hi', 'bn', 'pa']
en = json.load(io.open(os.path.join(D, 'en.json'), encoding='utf-8'))
table = {'en': en}
problems = []
counts = {'en': len(en)}
for lang in LANGS[1:]:
    p = os.path.join(D, lang + '.json')
    if not os.path.exists(p):
        problems.append('%s: no file' % lang); table[lang] = {}; counts[lang] = 0; continue
    t = json.load(io.open(p, encoding='utf-8'))
    missing = [k for k in en if k not in t or not str(t[k]).strip()]
    extra = [k for k in t if k not in en]
    for k in en:
        if k in t and t[k]:
            a, b = sorted(re.findall(r'%s|%d|\{\w+\}', en[k])), sorted(re.findall(r'%s|%d|\{\w+\}', str(t[k])))
            if a != b: problems.append('%s: %s placeholders %s vs %s' % (lang, k, a, b))
    if missing: problems.append('%s: %d missing (%s%s)' % (lang, len(missing), ', '.join(missing[:6]), '...' if len(missing) > 6 else ''))
    if extra: problems.append('%s: %d keys not in English (%s...)' % (lang, len(extra), ', '.join(extra[:4])))
    table[lang] = dict((k, t[k]) for k in en if k in t)
    counts[lang] = len(table[lang])
head = ('/* PandaStatusOS UI strings. Generated by the build from strings/en.json and the\n'
        '   per-language files beside it; edit those, not this. PS_STRINGS[lang][key]. */\n')
js = head + 'var PS_STRING_LANGS = %s;\nvar PS_STRINGS = %s;\n' % (
    json.dumps(LANGS), json.dumps(table, ensure_ascii=False, separators=(',', ':'), sort_keys=True))
io.open(os.path.join(D, 'ps_strings.js'), 'w', encoding='utf-8').write(js)
# A key that EXISTS but still carries the English text passes every check above: the key is
# there, the placeholders match, nothing is missing. All fifteen print-stage names shipped
# that way in all twenty-four tables, so every non-English reader saw English and nothing
# said so. Some words are legitimately the same in every language (AMS, DNS, PLA), so this
# cannot fail the build; it is counted and printed, and a number that jumps is the signal.
same = {}
for lang in LANGS[1:]:
    same[lang] = sum(1 for k in en if k in table[lang] and table[lang][k] == en[k])
print('untranslated (value identical to English):', json.dumps(same))
_worst = sorted(same.items(), key=lambda kv: -kv[1])[:3]
print('  most English-looking tables:', ', '.join('%s %d' % kv for kv in _worst))

print('keys per language:', json.dumps(counts))
print('ps_strings.js: %d bytes' % len(js.encode('utf-8')))
if problems:
    print('PROBLEMS:'); [print('  ', p) for p in problems]
    sys.exit(1)
print('every language carries every key; placeholders match')
