#!/usr/bin/env python3
"""
Generate the project's marks and favicon from primitives. Standard library only.

Provenance by construction. Every shape in every output is drawn by the code below from a
handful of numbers, so the origin of the artwork is this file and nothing else. Re-running
the script reproduces every byte; `--check` proves it by regenerating into a temporary
directory and comparing against what is committed. Nothing here is traced, imported, or
adapted from any image.

The mark is a light bar: a rounded housing holding four round LEDs, three lit, the fourth
dim, with a soft glow behind the lit ones. It depicts the product. It is not a panda, on
purpose; see docs/DECISIONS.md D-011.

Outputs, all under art/:
    mark-light.svg          the mark for light backgrounds, dark housing
    mark-dark.svg           the mark for dark backgrounds, light housing
    favicon-16.png
    favicon-32.png
    favicon-64.png          rasterised from the same primitives, 4x4 supersampled
    apple-touch-icon-180.png
    MARKS.md                what each file is, its size, its sha256, regenerated every run

Usage:
    python3 tools/art/gen_marks.py              regenerate everything into art/
    python3 tools/art/gen_marks.py --check      regenerate to a temp dir, diff, exit 1 on drift

The PNG encoder writes RGBA with filter type 0 on every row and zlib level 9. Both are
deterministic, and no timestamp or text chunk is written, so the bytes do not depend on
when or where the script ran.
"""

import argparse
import hashlib
import math
import os
import struct
import sys
import tempfile
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
ART = os.path.join(ROOT, "art")

# ---------------------------------------------------------------------------------------
# The drawing. One coordinate system, 96 x 96, used by the SVG and the rasteriser alike.
# ---------------------------------------------------------------------------------------

W = 96

# Colours are hex without alpha; alpha is a separate float so the rasteriser can
# composite. The lit colour is a green that holds up on both grounds; Q4 may retune it,
# and retuning is one edit here followed by a regenerate.
PALETTES = {
    "light": {  # for light page backgrounds
        "housing": "#1D1B20",
        "lit": "#2FA86A",
        "lit_hi": "#7FE0A8",
        "dim": "#4A484E",
        "glow": "#2FA86A",
    },
    "dark": {   # for dark page backgrounds
        "housing": "#E6E1E5",
        "lit": "#2FA86A",
        "lit_hi": "#7FE0A8",
        "dim": "#B8B3BC",
        "glow": "#2FA86A",
    },
}

# Geometry. Housing is a pill; four LEDs sit on its centreline.
HOUSING = dict(x=6, y=30, w=84, h=36, r=18)
LED_Y = 48
LED_R = 9.5
LED_HI_R = 3.6          # the small highlight dot, offset up-left, gives the LED a dome
LED_HI_DX, LED_HI_DY = -3.0, -3.2
LED_XS = [22, 40, 58, 76]
LIT = [True, True, True, False]
GLOW_R = 14.5
GLOW_ALPHA = 0.28


def shapes(palette):
    """The mark as an ordered list of primitives, back to front.

    Each is (kind, params, fill_hex, alpha). kind is 'rrect' or 'circle'.
    """
    p = PALETTES[palette]
    out = [("rrect", HOUSING, p["housing"], 1.0)]
    for x, lit in zip(LED_XS, LIT):
        if lit:
            out.append(("circle", dict(cx=x, cy=LED_Y, r=GLOW_R), p["glow"], GLOW_ALPHA))
    for x, lit in zip(LED_XS, LIT):
        out.append(("circle", dict(cx=x, cy=LED_Y, r=LED_R), p["lit"] if lit else p["dim"], 1.0))
        if lit:
            out.append(("circle", dict(cx=x + LED_HI_DX, cy=LED_Y + LED_HI_DY, r=LED_HI_R),
                        p["lit_hi"], 0.9))
    return out


# ---------------------------------------------------------------------------------------
# SVG
# ---------------------------------------------------------------------------------------

def fmt(v):
    s = f"{v:.2f}".rstrip("0").rstrip(".")
    return s if s else "0"


def svg(palette):
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {W}" width="{W}" height="{W}">',
        f'  <!-- generated by tools/art/gen_marks.py, palette {palette}. Do not edit; regenerate. -->',
    ]
    for kind, g, fill, a in shapes(palette):
        op = "" if a >= 1.0 else f' fill-opacity="{fmt(a)}"'
        if kind == "rrect":
            parts.append(f'  <rect x="{fmt(g["x"])}" y="{fmt(g["y"])}" width="{fmt(g["w"])}" '
                         f'height="{fmt(g["h"])}" rx="{fmt(g["r"])}" fill="{fill}"{op}/>')
        else:
            parts.append(f'  <circle cx="{fmt(g["cx"])}" cy="{fmt(g["cy"])}" r="{fmt(g["r"])}" '
                         f'fill="{fill}"{op}/>')
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------------------
# Rasteriser. Coverage by supersampling, alpha compositing back to front.
# ---------------------------------------------------------------------------------------

def hex_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def inside_rrect(px, py, g):
    x, y, w, h, r = g["x"], g["y"], g["w"], g["h"], g["r"]
    if px < x or px > x + w or py < y or py > y + h:
        return False
    # corner test
    cx = x + r if px < x + r else (x + w - r if px > x + w - r else None)
    cy = y + r if py < y + r else (y + h - r if py > y + h - r else None)
    if cx is None or cy is None:
        return True
    return (px - cx) ** 2 + (py - cy) ** 2 <= r * r


def inside_circle(px, py, g):
    return (px - g["cx"]) ** 2 + (py - g["cy"]) ** 2 <= g["r"] ** 2


def raster(palette, size, ss=4):
    """Return RGBA bytes, size x size, transparent background."""
    shp = [(kind, g, hex_rgb(fill), a) for kind, g, fill, a in shapes(palette)]
    scale = W / size
    rows = []
    sub = [(i + 0.5) / ss for i in range(ss)]
    for py in range(size):
        row = bytearray()
        for px in range(size):
            acc_r = acc_g = acc_b = acc_a = 0.0
            for sy in sub:
                uy = (py + sy) * scale
                for sx in sub:
                    ux = (px + sx) * scale
                    r = g_ = b = a = 0.0
                    for kind, g, (cr, cg, cb), ca in shp:
                        hit = inside_rrect(ux, uy, g) if kind == "rrect" else inside_circle(ux, uy, g)
                        if not hit:
                            continue
                        # source-over
                        r = cr * ca + r * (1 - ca)
                        g_ = cg * ca + g_ * (1 - ca)
                        b = cb * ca + b * (1 - ca)
                        a = ca + a * (1 - ca)
                    acc_r += r * (a if a else 0)  # premultiplied accumulation
                    acc_g += g_ * (a if a else 0)
                    acc_b += b * (a if a else 0)
                    acc_a += a
            n = ss * ss
            A = acc_a / n
            if A > 0:
                R = acc_r / acc_a
                G = acc_g / acc_a
                B = acc_b / acc_a
            else:
                R = G = B = 0.0
            row += bytes((int(round(R)), int(round(G)), int(round(B)), int(round(A * 255))))
        rows.append(bytes(row))
    return rows


def png(rows, size):
    def chunk(tag, data):
        c = struct.pack(">I", len(data)) + tag + data
        return c + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    ihdr = struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0)  # 8-bit RGBA
    raw = b"".join(b"\x00" + r for r in rows)                  # filter 0 each row
    idat = zlib.compress(raw, 9)
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", idat) + chunk(b"IEND", b"")


# ---------------------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------------------

OUTPUTS = [
    ("mark-light.svg", lambda: svg("light").encode()),
    ("mark-dark.svg", lambda: svg("dark").encode()),
    ("favicon-16.png", lambda: png(raster("light", 16), 16)),
    ("favicon-32.png", lambda: png(raster("light", 32), 32)),
    ("favicon-64.png", lambda: png(raster("light", 64), 64)),
    ("apple-touch-icon-180.png", lambda: png(raster("light", 180), 180)),
]


def build(outdir):
    os.makedirs(outdir, exist_ok=True)
    written = []
    for name, make in OUTPUTS:
        data = make()
        with open(os.path.join(outdir, name), "wb") as fh:
            fh.write(data)
        written.append((name, len(data), hashlib.sha256(data).hexdigest()))
    md = ["# Marks", "",
          "Generated by `tools/art/gen_marks.py`. Do not edit these files; edit the generator",
          "and re-run it. `python3 tools/art/gen_marks.py --check` proves the committed files",
          "are exactly what the generator produces.", "",
          "The mark is a light bar, the product itself. See `docs/DECISIONS.md` D-010 and D-011.", "",
          "| File | Bytes | sha256 |", "|---|---:|---|"]
    for name, n, h in written:
        md.append(f"| `{name}` | {n:,} | `{h}` |")
    md.append("")
    with open(os.path.join(outdir, "MARKS.md"), "w") as fh:
        fh.write("\n".join(md))
    return written


def check():
    with tempfile.TemporaryDirectory() as tmp:
        build(tmp)
        drift = []
        for name, _ in OUTPUTS + [("MARKS.md", None)]:
            a, b = os.path.join(ART, name), os.path.join(tmp, name)
            if not os.path.exists(a):
                drift.append(f"missing: art/{name}")
                continue
            if open(a, "rb").read() != open(b, "rb").read():
                drift.append(f"differs: art/{name}")
        if drift:
            print("DRIFT between art/ and the generator:")
            for d in drift:
                print("  " + d)
            return 1
        print(f"art/ matches the generator byte for byte ({len(OUTPUTS) + 1} files)")
        return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify art/ against a fresh build")
    ap.add_argument("--out", default=ART, help=argparse.SUPPRESS)
    args = ap.parse_args()
    if args.check:
        return check()
    for name, n, h in build(args.out):
        print(f"  {name:28s} {n:7,} B  {h[:16]}...")
    print(f"  wrote -> {os.path.relpath(args.out, ROOT)}/  (+ MARKS.md)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
